query flights {
  flights(pageSize: 1, page: 3) {
    pagination {
      total
      page
      pageSize
    }
    nodes {
      id
      code
      launchSite {
        name
        planet {
          name
        }
      }
      landingSite {
        name
        planet {
          name
        }
      }
    }
  }
}
